#!/usr/bin/perl -w

use v5.24;
use warnings;

use Astro::VO::VOTable;

defined $ARGV[0] or die( "usage: $0 <filename>\n" );
my $doc = Astro::VO::VOTable::Document->new_from_file($ARGV[0]) or die;
my $votable = $doc->get_VOTABLE or die;
my $resource = $votable->get_RESOURCE(0) or die;
my $table = $resource->get_TABLE(0) or die;
my $data = $table->get_DATA or die;
my $tabledata = $data->get_TABLEDATA or die;
my $num_rows = $table->get_num_rows or die;
my @field = $table->get_FIELD;
my $num_cols = @field;
print "num_rows = $num_rows, num_cols = $num_cols\n";

for my $i ( 0 .. $num_rows - 1 ) {
    my $tr = $tabledata->get_TR($i) or die;
    say "Row $i:";
    for my $j ( keys @field ) {
 	my $td = $tr->get_TD($j);
	say "Column $j (", $field[$j]->get_name, "): ", $td->get;
    }
}
